// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Waslah.Presistence;

#nullable disable

namespace Waslah.Presistence.migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250206195033_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Waslah.Entities.ChainedRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<int>("FirstLocId")
                        .HasColumnType("int");

                    b.Property<int>("LastLocId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfRides")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Time")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ChainedRoutes");
                });

            modelBuilder.Entity("Waslah.Entities.MyRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("PrimaryLocId")
                        .HasColumnType("int");

                    b.Property<int>("SecondaryLocId")
                        .HasColumnType("int");

                    b.Property<double>("Time")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryLocId");

                    b.HasIndex("SecondaryLocId");

                    b.ToTable("Routes");
                });

            modelBuilder.Entity("Waslah.Entities.RouteConnector", b =>
                {
                    b.Property<int>("MyRouteId")
                        .HasColumnType("int");

                    b.Property<int>("ChainedRouteID")
                        .HasColumnType("int");

                    b.Property<int>("RouteOrder")
                        .HasColumnType("int");

                    b.HasKey("MyRouteId", "ChainedRouteID");

                    b.HasIndex("ChainedRouteID");

                    b.ToTable("RouteConnectors");
                });

            modelBuilder.Entity("Waslah.Entities.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityNo")
                        .HasColumnType("int");

                    b.Property<int>("GovNo")
                        .HasColumnType("int");

                    b.Property<string>("Government")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("ModelId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StationNo")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("Waslah.Entities.StationType", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Name");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StationTypes");
                });

            modelBuilder.Entity("Waslah.Entities.MyRoute", b =>
                {
                    b.HasOne("Waslah.Entities.Station", "PriStation")
                        .WithMany("GoingRoute")
                        .HasForeignKey("PrimaryLocId")
                        .HasPrincipalKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Waslah.Entities.Station", "SecStation")
                        .WithMany("ReturnedRoute")
                        .HasForeignKey("SecondaryLocId")
                        .HasPrincipalKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriStation");

                    b.Navigation("SecStation");
                });

            modelBuilder.Entity("Waslah.Entities.RouteConnector", b =>
                {
                    b.HasOne("Waslah.Entities.ChainedRoute", "ChainedRoute")
                        .WithMany("RoutesInfo")
                        .HasForeignKey("ChainedRouteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Waslah.Entities.MyRoute", "MyRoute")
                        .WithMany("connectors")
                        .HasForeignKey("MyRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChainedRoute");

                    b.Navigation("MyRoute");
                });

            modelBuilder.Entity("Waslah.Entities.Station", b =>
                {
                    b.HasOne("Waslah.Entities.StationType", "StationType")
                        .WithMany("stations")
                        .HasForeignKey("Type");

                    b.Navigation("StationType");
                });

            modelBuilder.Entity("Waslah.Entities.ChainedRoute", b =>
                {
                    b.Navigation("RoutesInfo");
                });

            modelBuilder.Entity("Waslah.Entities.MyRoute", b =>
                {
                    b.Navigation("connectors");
                });

            modelBuilder.Entity("Waslah.Entities.Station", b =>
                {
                    b.Navigation("GoingRoute");

                    b.Navigation("ReturnedRoute");
                });

            modelBuilder.Entity("Waslah.Entities.StationType", b =>
                {
                    b.Navigation("stations");
                });
#pragma warning restore 612, 618
        }
    }
}
